spring:
  application:
    name: todaylunch
  jackson:
    mapper:
      accept-case-insensitive-enums: true
kakao:
  api:
    key: "13eebedc8dc823df7a6c15cd5ebacb04"
#    url: "https://dapi.kakao.com/v2/local/search/address.json"
    url: https://dapi.kakao.com/v2/local/search/keyword

